package com.wisesignsoft.OperationManagement.net.response;

/**
 * Created by ycs on 2016/12/6.
 */

public class OpenTepletResponse extends BaseResponse {

    /**
     * formDocument : &lt;?xml version="1.0" encoding="UTF-8"?&gt;
     &lt;BMForm-config&gt;
     &lt;BMForm bmModelName="inspection" superBmModelName="PROCESS_BASE" bmIcon="" bmHelp="" bmDisplayName="巡检管理" width="700" height="1500" order="0" modelName="INSPECTION" dmDisplayName="巡检管理" hasFlowChart="false" hasDataRelation="false" hasAuditRecord="false" hasOperLog="false" hasKB="false" hasbmHelp="true" conditionJudgment="" sortingSet="null" specificValueUpdate="{'values':[{'formItem':{'bmModelName':'in','isCanUpdate':true,'dmAttrDisplayName':'巡检状态','name':'巡检状态','dataProvider':null,'modelName':'INSPECTION','isFilterUser':false,'parentDeptJSON':null,'isCanAdd':true,'isVisible':true,'modified':false,'required':false,'sectionId':'Section0','dmAttrName':'IN_ISTA','isExecute':false,'value':'','isMult':false,'maxChars':null,'id':'combobox_1','nodeType':'ComboBox','srclib_label':'巡检状态','value_label':null,'ID':'combobox_1','isCanDelete':true,'configModifiedField':null,'seeHisWorkOrderInfo':false,'precision':null,'srclib':'xjzt','allColumnsJson':null},'formItemValue':{'value':'xjzt:bc87bd62-4aa6-43cc-92a0-35820cec7cb4','name':'新建'}},{'formItem':{'bmModelName':'in','isCanUpdate':true,'dmAttrDisplayName':'工单创建人','isExecute':false,'name':'创建人','dataProvider':null,'modelName':'INSPECTION','isFilterUser':false,'parentDeptJSON':null,'isVisible':true,'modified':false,'required':false,'sectionId':'Section0','dmAttrName':'IN_CREATER','srclib':'','value':'creator','isMult':false,'maxChars':null,'id':'datadisplayuser_3','nodeType':'DataDisplayUser','srclib_label':null,'value_label':'创建人','ID':'datadisplayuser_3','isCanDelete':true,'configModifiedField':null,'seeHisWorkOrderInfo':false,'precision':null,'isCanAdd':true,'allColumnsJson':null},'formItemValue':{'value':'creator','name':'创建人'}},{'formItem':{'bmModelName':'in','isCanUpdate':true,'dmAttrDisplayName':'创建时间','name':'创建时间','dataProvider':null,'modelName':'INSPECTION','isFilterUser':false,'parentDeptJSON':null,'isCanAdd':true,'isVisible':true,'modified':false,'required':false,'sectionId':'Section0','dmAttrName':'CREATEDATE','srclib':'','value':'currentTime','isMult':false,'maxChars':null,'id':'datadisplaydate_3','nodeType':'DataDisplayDate','srclib_label':null,'value_label':'当前时间','ID':'datadisplaydate_3','isCanDelete':true,'configModifiedField':null,'seeHisWorkOrderInfo':false,'precision':null,'isExecute':false,'allColumnsJson':null},'formItemValue':{'value':'currentTime','name':'当前时间'}}]}"&gt;
     &lt;BMFormValidate bmValidateJson=""/&gt;
     &lt;BMFormProcessor bmProcessorJson="null"/&gt;
     &lt;BMFormDataLinkage dataLinkageJson="null"/&gt;
     &lt;Section ID="Section0" label="巡检信息登记" isCurrent="true"&gt;
     &lt;BorderGroup ID="bordergroup_3" name="项目信息" y="23" styleJson="null" isVisible="true" x="43" width="642" height="173" seeHisWorkOrderInfo="false"/&gt;
     &lt;RadioButtons ID="radiobuttons_1" x="36" y="271" required="false" isVisible="true" dmAttrName="IN_FIR" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="是否首次巡检" srclib="yesorno" name="是否首次巡检" value="yesorno:bfb0d4b8-0f93-4c44-b124-b3a43e2c3798" seeHisWorkOrderInfo="false" srclib_label="是否" width="200" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;DateFeild ID="datefeild_1" x="399" hasDateTime="true" y="243" isUpdateBeforeDate="false" required="false" isVisible="true" isUpdateLaterDate="false" modified="false" bmModelName="inspection" seeHisWorkOrderInfo="false" dmAttrDisplayName="巡检日期" dmAttrName="IN_DATE" name="巡检日期" value="" hasBusinessKey="false" width="283" isDispatcherEvent="false" height="25" value_label="null"/&gt;
     &lt;RadioButtons ID="radiobuttons_2" x="60" y="241.15" required="false" isVisible="true" dmAttrName="IN_DL" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="是否异地" srclib="yesorno" name="是否异地" value="yesorno:bfb0d4b8-0f93-4c44-b124-b3a43e2c3798" seeHisWorkOrderInfo="false" srclib_label="是否" width="200" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;ComboBox ID="combobox_1" x="399" y="277.3" required="false" isVisible="true" dmAttrName="IN_ISTA" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="巡检状态" srclib="xjzt" name="巡检状态" value="xjzt:bc87bd62-4aa6-43cc-92a0-35820cec7cb4" seeHisWorkOrderInfo="false" srclib_label="巡检状态" width="279" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;RadioButtons ID="radiobuttons_3" x="41" y="411" required="false" isVisible="true" dmAttrName="IN_PCINT" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="PC网络巡检" srclib="wlxj" name="PC网络巡检" value="wlxj:8b567ae4-42ce-4b48-b7aa-a4ec64a7ed75" seeHisWorkOrderInfo="false" srclib_label="PC网络巡检" width="353" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;RadioButtons ID="radiobuttons_4" x="56" y="343" required="false" isVisible="true" dmAttrName="IN_DI" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="设备巡检" srclib="sbxj" name="设备巡检" value="sbxj:ecb47d2d-d4dd-4d8b-be04-9154a7cbda4b" seeHisWorkOrderInfo="false" srclib_label="设备巡检" width="234" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;RadioButtons ID="radiobuttons_5" x="44" y="379" required="false" isVisible="true" dmAttrName="IN_DB" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="数据库巡检" srclib="dbxj" name="数据库巡检" value="dbxj:faca70f7-b155-481f-9ad1-8485c21c3e85" seeHisWorkOrderInfo="false" srclib_label="数据库巡检" width="334" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;ComboBox ID="combobox_3" x="24" y="305.15" required="false" isVisible="true" dmAttrName="IN_ESUB" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="新增属性" srclib="is_wota" name="工程师所属区域" value="is_wota:26c3a2ab-15da-4c1f-be66-87a9c2104699" seeHisWorkOrderInfo="false" srclib_label="工作量归属区域" width="313" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;ResModelSelect ID="resmodelselect_1" allColumnsJson="null" y="41" hasBusinessKey="false" isVisible="true" dmAttrName="OBJ_PROI" x="118" modified="false" queryScope="" bmModelName="inspection" realTimeUpdate="true" dmAttrDisplayName="项目信息" name="项目选择" value="" isMult="false" resModelValueJson="{'bmDisplayName':'合同信息','bmModelName':'inspection','configValueJson':[{'mx_internal_uid':'8141A790-4E3F-C260-B1DE-C86824B690A7','fromDmAttrName':{'id':'textinput_8','dmAttrName':'IN_CUNAA'},'toFmAttrName':{'id':'textinput_2','dmAttrName':'CUST_NAME'}},{'mx_internal_uid':'F3620B0A-2973-3925-B104-C86854D7285D','fromDmAttrName':{'id':'textinput_9','dmAttrName':'IN_PRONO'},'toFmAttrName':{'id':'textinput_4','dmAttrName':'PROJ_NO'}},{'mx_internal_uid':'A4FA38E1-DBE4-B2D7-3790-C8687A13C631','fromDmAttrName':{'id':'textinput_10','dmAttrName':'IN_PRONA'},'toFmAttrName':{'id':'textinput_5','dmAttrName':'PROJ_NAME'}},{'mx_internal_uid':'9E721224-7D27-CB4B-8FC4-C8689602F0E1','fromDmAttrName':{'id':'datefeild_2','dmAttrName':'IN_STATT'},'toFmAttrName':{'id':'datadisplaydate_1','dmAttrName':'PROJ_SD'}},{'mx_internal_uid':'CA85A549-3977-BBEC-E3ED-C868B85F89F2','fromDmAttrName':{'id':'datefeild_3','dmAttrName':'IN_ENDT'},'toFmAttrName':{'id':'datadisplaydate_2','dmAttrName':'PROJ_ED'}},{'mx_internal_uid':'925E07FD-A1D7-32DC-9BC8-C868D6D9AA21','fromDmAttrName':{'id':'combobox_5','dmAttrName':'IN_INRATE'},'toFmAttrName':{'id':'radiobuttons_5','dmAttrName':'PROJ_PI'}},{'mx_internal_uid':'AE90D845-18D8-A875-056F-7C3476E5E327','fromDmAttrName':{'id':'textinput_7','dmAttrName':'IN_NO'},'toFmAttrName':{'id':'textinput_1','dmAttrName':'CUST_NO'}}],'dmAttrName':'OBJ_PROI','dmDisplayName':'合同信息','toBmModelName':'CONTRACTS'}" width="170" isDispatcherEvent="false" height="25" seeHisWorkOrderInfo="false" required="false"/&gt;
     &lt;TextInput ID="textinput_7" x="63" y="75" required="false" isVisible="true" dmAttrName="IN_NO" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="客户编码" name="客户编号" value="" identityRule="null" width="287" isDispatcherEvent="false" height="23" maxChars="85" seeHisWorkOrderInfo="false"/&gt;
     &lt;TextInput ID="textinput_8" x="357" y="75" required="false" isVisible="true" dmAttrName="IN_CUNAA" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="客户姓名" name="客户名称" value="" identityRule="null" width="306" isDispatcherEvent="false" height="23" maxChars="85" seeHisWorkOrderInfo="false"/&gt;
     &lt;TextInput ID="textinput_9" x="63" y="101" required="false" isVisible="true" dmAttrName="IN_PRONO" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="项目编码" name="项目编号" value="" identityRule="null" width="287" isDispatcherEvent="false" height="23" maxChars="85" seeHisWorkOrderInfo="false"/&gt;
     &lt;TextInput ID="textinput_10" x="356.5" y="101" required="false" isVisible="true" dmAttrName="IN_PRONA" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="项目名称" name="项目名称" value="" identityRule="null" width="307" isDispatcherEvent="false" height="23" maxChars="85" seeHisWorkOrderInfo="false"/&gt;
     &lt;DateFeild ID="datefeild_2" x="63" hasDateTime="true" y="129" isUpdateBeforeDate="false" required="false" isVisible="true" isUpdateLaterDate="false" modified="false" bmModelName="inspection" seeHisWorkOrderInfo="false" dmAttrDisplayName="起始日期" dmAttrName="IN_STATT" name="起始日期" value="" hasBusinessKey="false" width="280" isDispatcherEvent="false" height="25" value_label=""/&gt;
     &lt;DateFeild ID="datefeild_3" x="357" hasDateTime="true" y="128" isUpdateBeforeDate="false" required="false" isVisible="true" isUpdateLaterDate="false" modified="false" bmModelName="inspection" seeHisWorkOrderInfo="false" dmAttrDisplayName="结束日期" dmAttrName="IN_ENDT" name="结束日期" value="" hasBusinessKey="false" width="306" isDispatcherEvent="false" height="25" value_label=""/&gt;
     &lt;ComboBox ID="combobox_5" x="62" y="158" required="false" isVisible="true" dmAttrName="IN_INRATE" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="巡检周期" srclib="PROJ_PI" name="巡检周期" value="" seeHisWorkOrderInfo="false" srclib_label="巡检周期" width="278" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;DataDisplayUser ID="datadisplayuser_3" x="100" width="240" y="491" required="false" isVisible="true" dmAttrName="IN_CREATER" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="工单创建人" name="创建人" value="creator" displayName="" height="23" value_label="创建人" seeHisWorkOrderInfo="false"/&gt;
     &lt;TextInput ID="textinput_11" x="97" y="562" required="false" isVisible="false" dmAttrName="PIKEY" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="单号" name="单号" value="" identityRule="null" width="200" isDispatcherEvent="false" height="23" maxChars="16" seeHisWorkOrderInfo="false"/&gt;
     &lt;DataDisplayDate ID="datadisplaydate_3" x="386" width="240" y="491" required="false" isVisible="true" dmAttrName="IN_CREATT" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="工单创建时间" name="创建时间" value="currentTime" displayName="2016-12-06 20:05:54" height="23" value_label="当前时间" seeHisWorkOrderInfo="false"/&gt;
     &lt;Position ID="position_1" x="97.5" y="605.5" required="false" isVisible="false" dmAttrName="CUST_LOCATE" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="客户位置" name="位置" value="" identityRule="null" width="200" isDispatcherEvent="false" height="23" maxChars="85" seeHisWorkOrderInfo="false"/&gt;
     &lt;TextArea ID="textarea_5" x="60" y="203" required="false" isVisible="true" addToItemIds="" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="工单标题" dmAttrName="TITLE" name="巡检标题" value="rrrr" seeHisWorkOrderInfo="false" width="609" isDispatcherEvent="false" height="25" maxChars="85"/&gt;
     &lt;Label ID="label_1" name="分区" y="349" styleJson="null" isVisible="true" x="589" width="50" height="23" seeHisWorkOrderInfo="false"/&gt;
     &lt;Label ID="label_2" name="套" y="384" styleJson="null" isVisible="true" x="591" width="50" height="23" seeHisWorkOrderInfo="false"/&gt;
     &lt;Label ID="label_3" name="台" y="415" styleJson="null" isVisible="true" x="591" width="50" height="23" seeHisWorkOrderInfo="false"/&gt;
     &lt;NumericStepper ID="numericstepper_1" x="398" y="343" required="false" isVisible="true" dmAttrName="IN_DP" modified="false" precision="0" bmModelName="inspection" seeHisWorkOrderInfo="false" dmAttrDisplayName="设备分区" name="设备分区" value="" hasBusinessKey="false" width="180" inputLength="5" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;NumericStepper ID="numericstepper_2" x="386" y="377" required="false" isVisible="true" dmAttrName="IN_DBC" modified="false" precision="0" bmModelName="inspection" seeHisWorkOrderInfo="false" dmAttrDisplayName="数据库套数" name="数据库套数" value="" hasBusinessKey="false" width="192" inputLength="5" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;NumericStepper ID="numericstepper_3" x="407" y="409" required="false" isVisible="true" dmAttrName="IN_PCC" modified="false" precision="0" bmModelName="inspection" seeHisWorkOrderInfo="false" dmAttrDisplayName="PC数目" name="PC台数" value="" hasBusinessKey="false" width="171" inputLength="5" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;/Section&gt;
     &lt;Section ID="Section1" label="巡检记录"&gt;
     &lt;BorderGroup ID="bordergroup_1" name="客户评价" y="501.05" styleJson="{'titleFontWeight':'normal','borderAlpha':1,'titleFontSize':12,'borderThickness':1,'borderColor':10799340,'cornerRadius':4}" isVisible="true" x="73.85" width="544" height="138" seeHisWorkOrderInfo="false"/&gt;
     &lt;TextArea ID="textarea_1" x="41.85" y="134.9" required="false" isVisible="true" addToItemIds="" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="异常处理及建议" dmAttrName="IN_EH" name="异常处理及建议" value="" seeHisWorkOrderInfo="false" width="565" isDispatcherEvent="false" height="88" maxChars="85"/&gt;
     &lt;TextInput ID="textinput_4" x="77.35" y="233.95" required="false" isVisible="true" dmAttrName="IN_RW" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="风险提示" name="风险提示" value="" identityRule="null" width="531" isDispatcherEvent="false" height="23" maxChars="85" seeHisWorkOrderInfo="false"/&gt;
     &lt;RadioButtons ID="radiobuttons_6" x="53.85" y="270.05" required="false" isVisible="true" dmAttrName="IN_WT" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="是否工作时间" srclib="yesorno" name="是否工作时间" value="" seeHisWorkOrderInfo="false" srclib_label="是否" width="200" isDispatcherEvent="false" height="23" value_label=""/&gt;
     &lt;ComboBox ID="combobox_4" x="41.85" y="304.3" required="false" isVisible="true" dmAttrName="IN_NIHT" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="非独立完成处理方式" srclib="clfs" name="非独立处理方式" value="" seeHisWorkOrderInfo="false" srclib_label="巡检处理方式" width="262" isDispatcherEvent="false" height="23" value_label="null"/&gt;
     &lt;SingleUserChoose ID="singleuserchoose_1" x="336.85" y="257.05" required="false" isVisible="true" dmAttrName="IN_SP" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="支持人员" name="支持人员" value="" isShowBorder="true" personInfo="[{'label':'部门','id':'department'},{'label':'姓名','id':'userName'}]" width="279" height="111" value_label="" seeHisWorkOrderInfo="false"/&gt;
     &lt;TextArea ID="textarea_2" x="101.85" y="380.05" required="false" isVisible="true" addToItemIds="" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="备注" dmAttrName="IN_B" name="备注" value="" seeHisWorkOrderInfo="false" width="510" isDispatcherEvent="false" height="107" maxChars="0"/&gt;
     &lt;RadioButtons ID="radiobuttons_7" x="112.85" y="529.45" required="false" isVisible="true" dmAttrName="IN_SE" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="满意度评价" srclib="mydpj" name="满意度评价" value="" seeHisWorkOrderInfo="false" srclib_label="满意度评价" width="272" isDispatcherEvent="false" height="23" value_label=""/&gt;
     &lt;TextInput ID="textinput_5" x="123.85" y="557.2" required="false" isVisible="true" dmAttrName="IN_CUNA" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="客户姓名" name="客户姓名" value="" identityRule="null" width="281" isDispatcherEvent="false" height="23" maxChars="85" seeHisWorkOrderInfo="false"/&gt;
     &lt;Attachment ID="attachment_1" isDeleteAttachment="false" templateJson="" required="false" isVisible="true" dmAttrName="IN_UPLO" x="58.85" modified="false" y="645.2" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="巡检汇总上传" name="巡检汇总上传" value="" width="566" height="169" seeHisWorkOrderInfo="false"/&gt;
     &lt;DataDisplayUser ID="datadisplayuser_1" x="47.5" width="240" y="852.95" required="false" isVisible="true" dmAttrName="IN_EN" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="工程师" name="工程师" value="" displayName="" height="23" value_label="" seeHisWorkOrderInfo="false"/&gt;
     &lt;DataDisplayDate ID="datadisplaydate_4" x="352.9" width="240" y="853.1" required="false" isVisible="true" dmAttrName="IN_RET" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="巡检登记时间" name="巡检登记时间" value="" displayName="" height="23" value_label="" seeHisWorkOrderInfo="false"/&gt;
     &lt;TextInput ID="textinput_13" x="100.85" y="593.7" required="false" isVisible="true" dmAttrName="IN_CUCOM" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="客户联系方式" name="客户联系方式" value="" identityRule="null" width="306" isDispatcherEvent="false" height="23" maxChars="33" seeHisWorkOrderInfo="false"/&gt;
     &lt;TextArea ID="textarea_6" x="56" y="35.65" required="false" isVisible="true" addToItemIds="" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="异常情况描述" dmAttrName="IN_DESCRIBE" name="异常情况描述" value="" seeHisWorkOrderInfo="false" width="547" isDispatcherEvent="false" height="82" maxChars="85"/&gt;
     &lt;TextInput ID="textinput_14" x="18.4" y="333.2" required="false" isVisible="true" dmAttrName="IN_SEVER" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="服务地点" name="服务地点（城市名）" value="" identityRule="null" width="285" isDispatcherEvent="false" height="23" maxChars="85" seeHisWorkOrderInfo="false"/&gt;
     &lt;/Section&gt;
     &lt;Section ID="Section2" label="审核"&gt;
     &lt;RadioButtons ID="radiobuttons_8" x="121" y="31" required="false" isVisible="true" dmAttrName="IN_CHE" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="审核是否通过" srclib="yesorno" name="审核是否通过" value="" seeHisWorkOrderInfo="false" srclib_label="是否" width="200" isDispatcherEvent="false" height="23" value_label=""/&gt;
     &lt;TextArea ID="textarea_3" x="42" y="71" required="false" isVisible="true" addToItemIds="" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="审核意见" dmAttrName="IN_CHES" name="审核意见" value="" seeHisWorkOrderInfo="false" width="571" isDispatcherEvent="false" height="120" maxChars="0"/&gt;
     &lt;DataDisplayUser ID="datadisplayuser_6" x="111" width="240" y="238.6" required="false" isVisible="true" dmAttrName="IN_SHR" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="审核人" name="审核人" value="" displayName="" height="23" value_label="" seeHisWorkOrderInfo="false"/&gt;
     &lt;DataDisplayDate ID="datadisplaydate_6" x="361" width="295" y="237" required="false" isVisible="true" dmAttrName="IN_SHSJ" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="审核时间" name="审核时间" value="" displayName="" height="23" value_label="" seeHisWorkOrderInfo="false"/&gt;
     &lt;/Section&gt;
     &lt;Section ID="Section3" label="表单核对"&gt;
     &lt;BorderGroup ID="bordergroup_2" name="不良行为选项" y="21" styleJson="null" isVisible="true" x="38" width="634" height="127" seeHisWorkOrderInfo="false"/&gt;
     &lt;RadioButtons ID="radiobuttons_9" x="70" y="47" required="false" isVisible="true" dmAttrName="IN_IBC" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="不良行为" srclib="yesorno" name="不良行为" value="" seeHisWorkOrderInfo="false" srclib_label="是否" width="200" isDispatcherEvent="false" height="23" value_label=""/&gt;
     &lt;CheckBox ID="checkbox_1" x="39" y="167" required="false" isVisible="true" dmAttrName="IN_FICO" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="填写不完整分类" srclib="txbwz" name="填写不完整分类" value="" seeHisWorkOrderInfo="false" srclib_label="填写不完整分类" width="419" isDispatcherEvent="false" height="101" value_label=""/&gt;
     &lt;DataDisplayDate ID="datadisplaydate_5" x="356" width="240" y="339.3" required="false" isVisible="true" dmAttrName="IN_CHET" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="审核时间" name="核对时间" value="" displayName="" height="23" value_label="" seeHisWorkOrderInfo="false"/&gt;
     &lt;RadioButtons ID="radiobuttons_13" x="39" y="280" required="false" isVisible="true" dmAttrName="IN_CLSTA" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="关闭状态" srclib="gbzt" name="关闭状态" value="" seeHisWorkOrderInfo="false" srclib_label="关闭状态" width="397" isDispatcherEvent="false" height="23" value_label=""/&gt;
     &lt;DataDisplayUser ID="datadisplayuser_5" x="39" width="240" y="339.3" required="false" isVisible="true" dmAttrName="IN_CHEP" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="审核人" name="核对人" value="" displayName="" height="23" value_label="" seeHisWorkOrderInfo="false"/&gt;
     &lt;RadioButtons ID="radiobuttons_14" x="60" y="79" required="false" isVisible="true" dmAttrName="IN_OMM" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="OMM系统" srclib="OMMxitong" name="OMM系统" value="" seeHisWorkOrderInfo="false" srclib_label="OMM系统" width="600" isDispatcherEvent="false" height="23" value_label=""/&gt;
     &lt;RadioButtons ID="radiobuttons_15" x="94" y="114" required="false" isVisible="true" dmAttrName="IN_PAP" modified="false" bmModelName="inspection" hasBusinessKey="false" dmAttrDisplayName="纸件" srclib="zhijian" name="纸件" value="" seeHisWorkOrderInfo="false" srclib_label="纸件" width="545" isDispatcherEvent="false" height="23" value_label=""/&gt;
     &lt;/Section&gt;
     &lt;Button ID="submit"&gt;&lt;nextNode name="登记--记录" to="记录" isDefaultPath="true" taskStrategy="{'strategyKey':'creator','strategyValue':''}" specificValueUpdate="{'values':[{'formItem':{'sectionId':'Section0','dmAttrName':'IN_ISTA','isVisible':true,'srclib':'xjzt','isMult':false,'name':'巡检状态','isExecute':false,'srclib_label':'巡检状态','dataProvider':null,'value_label':null,'isCanDelete':true,'configModifiedField':null,'seeHisWorkOrderInfo':false,'required':false,'isCanAdd':true,'allColumnsJson':null,'value':'','maxChars':null,'id':'combobox_1','bmModelName':'in','isCanUpdate':true,'dmAttrDisplayName':'巡检状态','isFilterUser':false,'ID':'combobox_1','modelName':'INSPECTION','nodeType':'ComboBox','precision':null,'modified':false,'parentDeptJSON':null},'formItemValue':{'value':'xjzt:c937612b-c693-454b-a3ae-ec92401b7423','name':'巡检中'}}]}" nameDesc="记录" isDependCondition="false"/&gt;&lt;/Button&gt;
     &lt;/BMForm&gt;
     &lt;/BMForm-config&gt;
     * PROCESS_KEY : inspection
     */

    private ReturnValueBean returnValue;

    public ReturnValueBean getReturnValue() {
        return returnValue;
    }

    public void setReturnValue(ReturnValueBean returnValue) {
        this.returnValue = returnValue;
    }

    public static class ReturnValueBean {
        private String formDocument;
        private String PROCESS_KEY;

        public String getFormDocument() {
            return formDocument;
        }

        public void setFormDocument(String formDocument) {
            this.formDocument = formDocument;
        }

        public String getPROCESS_KEY() {
            return PROCESS_KEY;
        }

        public void setPROCESS_KEY(String PROCESS_KEY) {
            this.PROCESS_KEY = PROCESS_KEY;
        }
    }
}
